[project]
name = "genomic-alignment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.13.3",
    "flyte>=2.0.0b43",
    "mashumaro>=3.17",
    "requests>=2.32.5",
]
