[project]
name = "ml-workflow"
version = "0.1.0"
description = "Machine learning example"
readme = "README.md"
requires-python = ">=3.9,<3.13"
dependencies = [
    "scikit-learn==1.4.1.post1",
    "pandas==2.2.1",
    "matplotlib==3.8.3",
    "pyarrow==17.0.0",
    "union==0.1.132",
]
